-- ============================================================
-- TABLE: service_feature_snapshots
-- Purpose:
-- Stores aggregated & engineered feature snapshots
-- generated by the pipeline (one row per service per run).
-- ============================================================

create table if not exists service_feature_snapshots (

    -- Unique row identifier
    id uuid primary key default gen_random_uuid(),

    -- Technical insert timestamp (when row was written to DB)
    created_at timestamptz not null default now(),

    -- Logical pipeline execution time (same for all services in one run)
    run_timestamp timestamptz not null,

    -- Service identifier (e.g. go, python, node)
    service text not null,

    -- Core latency percentiles (in seconds)
    p50_latency_s numeric not null,
    p95_latency_s numeric not null,
    p99_latency_s numeric not null,

    -- Tail behavior indicators
    tail_ratio_p95_p50 numeric not null,
    tail_ratio_p99_p95 numeric not null,

    -- Success rate (0.0 – 1.0)
    success_rate numeric not null
);

-- ============================================================
-- Prevent duplicate rows for same service & pipeline run
-- (important for retry safety in cron jobs)
-- ============================================================

alter table service_feature_snapshots
add constraint unique_service_per_run
unique (service, run_timestamp);

-- ============================================================
-- Index for fast time-based queries (latest snapshots)
-- ============================================================

create index if not exists idx_sfs_run_timestamp
on service_feature_snapshots (run_timestamp desc);

-- ============================================================
-- Index for fast filtering by service
-- ============================================================

create index if not exists idx_sfs_service
on service_feature_snapshots (service);
